"""Unit type definitions — fheroes2 exact stats (M7: all factions).

All 6 factions + neutral units with original HoMM2 data extracted from
``fheroes2/src/fheroes2/monster/monster_info.cpp``.

Fields:
  attack, defense, hp, speed   — combat stats  (speed = Speed enum value)
  damage_min, damage_max       — per-creature damage range
  shots                        — ranged ammo  (0 = melee only, >0 = archer)
  grown                        — weekly growth rate  (default ``count`` for presets)
  count                        — default army size (= grown for canonical data)
  is_archer                    — True when shots > 0
  is_flying, is_wide           — movement / footprint flags
  abilities                    — list of special-ability tags
  ability_params               — dict of ability parameters (e.g. spell_caster details)
  race                         — faction  (Knight / Barbarian / Sorceress / …)
  level                        — tier 1–6
  cost                         — gold cost per creature
  symbol                       — display character  (ASCII / headless)
"""

UNIT_TYPES = {
    # ── Knight (Race::KNGT) ────────────────────────────────────────────
    "Peasant": {
        "attack": 1, "defense": 1, "hp": 1, "speed": 2,
        "damage_min": 1, "damage_max": 1,
        "shots": 0, "grown": 12, "count": 12,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Knight", "level": 1, "cost": 20,
        "symbol": "Pe",
    },
    "Archer": {
        "attack": 5, "defense": 3, "hp": 10, "speed": 2,
        "damage_min": 2, "damage_max": 3,
        "shots": 12, "grown": 8, "count": 8,
        "is_archer": True, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Knight", "level": 2, "cost": 150,
        "symbol": "Ar",
    },
    "Ranger": {
        "attack": 5, "defense": 3, "hp": 10, "speed": 4,
        "damage_min": 2, "damage_max": 3,
        "shots": 24, "grown": 8, "count": 8,
        "is_archer": True, "is_flying": False, "is_wide": False,
        "abilities": ["double_shooting"], "ability_params": {},
        "race": "Knight", "level": 2, "cost": 200,
        "symbol": "Rn",
    },
    "Pikeman": {
        "attack": 5, "defense": 9, "hp": 15, "speed": 4,
        "damage_min": 3, "damage_max": 4,
        "shots": 0, "grown": 5, "count": 5,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Knight", "level": 3, "cost": 200,
        "symbol": "Pi",
    },
    "Veteran Pikeman": {
        "attack": 5, "defense": 9, "hp": 20, "speed": 5,
        "damage_min": 3, "damage_max": 4,
        "shots": 0, "grown": 5, "count": 5,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Knight", "level": 3, "cost": 250,
        "symbol": "VP",
    },
    "Swordsman": {
        "attack": 7, "defense": 9, "hp": 25, "speed": 4,
        "damage_min": 4, "damage_max": 6,
        "shots": 0, "grown": 4, "count": 4,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Knight", "level": 4, "cost": 250,
        "symbol": "Sw",
    },
    "Master Swordsman": {
        "attack": 7, "defense": 9, "hp": 30, "speed": 5,
        "damage_min": 4, "damage_max": 6,
        "shots": 0, "grown": 4, "count": 4,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Knight", "level": 4, "cost": 300,
        "symbol": "MS",
    },
    "Cavalry": {
        "attack": 10, "defense": 9, "hp": 30, "speed": 6,
        "damage_min": 5, "damage_max": 10,
        "shots": 0, "grown": 3, "count": 3,
        "is_archer": False, "is_flying": False, "is_wide": True,
        "abilities": [], "ability_params": {},
        "race": "Knight", "level": 5, "cost": 300,
        "symbol": "Ca",
    },
    "Champion": {
        "attack": 10, "defense": 9, "hp": 40, "speed": 7,
        "damage_min": 5, "damage_max": 10,
        "shots": 0, "grown": 3, "count": 3,
        "is_archer": False, "is_flying": False, "is_wide": True,
        "abilities": [], "ability_params": {},
        "race": "Knight", "level": 5, "cost": 375,
        "symbol": "Ch",
    },
    "Paladin": {
        "attack": 11, "defense": 12, "hp": 50, "speed": 5,
        "damage_min": 10, "damage_max": 20,
        "shots": 0, "grown": 2, "count": 2,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": ["double_melee"], "ability_params": {},
        "race": "Knight", "level": 6, "cost": 600,
        "symbol": "Pa",
    },
    "Crusader": {
        "attack": 11, "defense": 12, "hp": 65, "speed": 6,
        "damage_min": 10, "damage_max": 20,
        "shots": 0, "grown": 2, "count": 2,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": ["double_melee", "double_damage_to_undead"],
        "ability_params": {},
        "race": "Knight", "level": 6, "cost": 1000,
        "symbol": "Cr",
    },

    # ── Barbarian (Race::BARB) ─────────────────────────────────────────
    "Goblin": {
        "attack": 3, "defense": 1, "hp": 3, "speed": 4,
        "damage_min": 1, "damage_max": 2,
        "shots": 0, "grown": 10, "count": 10,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Barbarian", "level": 1, "cost": 40,
        "symbol": "Go",
    },
    "Orc": {
        "attack": 3, "defense": 4, "hp": 10, "speed": 2,
        "damage_min": 2, "damage_max": 3,
        "shots": 8, "grown": 8, "count": 8,
        "is_archer": True, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Barbarian", "level": 2, "cost": 140,
        "symbol": "Or",
    },
    "Orc Chief": {
        "attack": 3, "defense": 4, "hp": 15, "speed": 3,
        "damage_min": 3, "damage_max": 4,
        "shots": 16, "grown": 8, "count": 8,
        "is_archer": True, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Barbarian", "level": 2, "cost": 175,
        "symbol": "OC",
    },
    "Wolf": {
        "attack": 6, "defense": 2, "hp": 20, "speed": 6,
        "damage_min": 3, "damage_max": 5,
        "shots": 0, "grown": 5, "count": 5,
        "is_archer": False, "is_flying": False, "is_wide": True,
        "abilities": ["double_melee"], "ability_params": {},
        "race": "Barbarian", "level": 3, "cost": 200,
        "symbol": "Wo",
    },
    "Ogre": {
        "attack": 9, "defense": 5, "hp": 40, "speed": 2,
        "damage_min": 4, "damage_max": 6,
        "shots": 0, "grown": 4, "count": 4,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Barbarian", "level": 4, "cost": 300,
        "symbol": "Og",
    },
    "Ogre Lord": {
        "attack": 9, "defense": 5, "hp": 60, "speed": 4,
        "damage_min": 5, "damage_max": 7,
        "shots": 0, "grown": 4, "count": 4,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Barbarian", "level": 4, "cost": 500,
        "symbol": "OL",
    },
    "Troll": {
        "attack": 10, "defense": 5, "hp": 40, "speed": 4,
        "damage_min": 5, "damage_max": 7,
        "shots": 8, "grown": 3, "count": 3,
        "is_archer": True, "is_flying": False, "is_wide": False,
        "abilities": ["self_heal"], "ability_params": {},
        "race": "Barbarian", "level": 5, "cost": 600,
        "symbol": "Tr",
    },
    "War Troll": {
        "attack": 10, "defense": 5, "hp": 40, "speed": 5,
        "damage_min": 7, "damage_max": 9,
        "shots": 16, "grown": 3, "count": 3,
        "is_archer": True, "is_flying": False, "is_wide": False,
        "abilities": ["self_heal"], "ability_params": {},
        "race": "Barbarian", "level": 5, "cost": 700,
        "symbol": "WT",
    },
    "Cyclops": {
        "attack": 12, "defense": 9, "hp": 80, "speed": 5,
        "damage_min": 12, "damage_max": 24,
        "shots": 0, "grown": 2, "count": 2,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": ["two_cell_melee", "spell_caster"],
        "ability_params": {"spell_caster": {"spell": "paralyze", "chance": 20}},
        "race": "Barbarian", "level": 6, "cost": 750,
        "symbol": "Cy",
    },

    # ── Sorceress (Race::SORC) ─────────────────────────────────────────
    "Sprite": {
        "attack": 4, "defense": 2, "hp": 2, "speed": 4,
        "damage_min": 1, "damage_max": 2,
        "shots": 0, "grown": 8, "count": 8,
        "is_archer": False, "is_flying": True, "is_wide": False,
        "abilities": ["no_enemy_retaliation"], "ability_params": {},
        "race": "Sorceress", "level": 1, "cost": 50,
        "symbol": "Sp",
    },
    "Dwarf": {
        "attack": 6, "defense": 5, "hp": 20, "speed": 2,
        "damage_min": 2, "damage_max": 4,
        "shots": 0, "grown": 6, "count": 6,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": ["magic_resistance"],
        "ability_params": {"magic_resistance": {"chance": 25}},
        "race": "Sorceress", "level": 2, "cost": 200,
        "symbol": "Dw",
    },
    "Battle Dwarf": {
        "attack": 6, "defense": 6, "hp": 20, "speed": 4,
        "damage_min": 2, "damage_max": 4,
        "shots": 0, "grown": 6, "count": 6,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": ["magic_resistance"],
        "ability_params": {"magic_resistance": {"chance": 25}},
        "race": "Sorceress", "level": 2, "cost": 250,
        "symbol": "BD",
    },
    "Elf": {
        "attack": 4, "defense": 3, "hp": 15, "speed": 4,
        "damage_min": 2, "damage_max": 3,
        "shots": 24, "grown": 4, "count": 4,
        "is_archer": True, "is_flying": False, "is_wide": False,
        "abilities": ["double_shooting"], "ability_params": {},
        "race": "Sorceress", "level": 3, "cost": 250,
        "symbol": "El",
    },
    "Grand Elf": {
        "attack": 5, "defense": 5, "hp": 15, "speed": 6,
        "damage_min": 2, "damage_max": 3,
        "shots": 24, "grown": 4, "count": 4,
        "is_archer": True, "is_flying": False, "is_wide": False,
        "abilities": ["double_shooting"], "ability_params": {},
        "race": "Sorceress", "level": 3, "cost": 300,
        "symbol": "GE",
    },
    "Druid": {
        "attack": 7, "defense": 5, "hp": 25, "speed": 5,
        "damage_min": 5, "damage_max": 8,
        "shots": 8, "grown": 3, "count": 3,
        "is_archer": True, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Sorceress", "level": 4, "cost": 350,
        "symbol": "Dr",
    },
    "Greater Druid": {
        "attack": 7, "defense": 7, "hp": 25, "speed": 6,
        "damage_min": 5, "damage_max": 8,
        "shots": 16, "grown": 3, "count": 3,
        "is_archer": True, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Sorceress", "level": 4, "cost": 400,
        "symbol": "GD",
    },
    "Unicorn": {
        "attack": 10, "defense": 9, "hp": 40, "speed": 5,
        "damage_min": 7, "damage_max": 14,
        "shots": 0, "grown": 2, "count": 2,
        "is_archer": False, "is_flying": False, "is_wide": True,
        "abilities": ["spell_caster"],
        "ability_params": {"spell_caster": {"spell": "blind", "chance": 20}},
        "race": "Sorceress", "level": 5, "cost": 500,
        "symbol": "Un",
    },
    "Phoenix": {
        "attack": 12, "defense": 10, "hp": 100, "speed": 7,
        "damage_min": 20, "damage_max": 40,
        "shots": 0, "grown": 1, "count": 1,
        "is_archer": False, "is_flying": True, "is_wide": True,
        "abilities": ["two_cell_melee"], "ability_params": {},
        "race": "Sorceress", "level": 6, "cost": 1500,
        "symbol": "Ph",
    },

    # ── Warlock (Race::WRLK) ───────────────────────────────────────────
    "Centaur": {
        "attack": 3, "defense": 1, "hp": 5, "speed": 4,
        "damage_min": 1, "damage_max": 2,
        "shots": 8, "grown": 8, "count": 8,
        "is_archer": True, "is_flying": False, "is_wide": True,
        "abilities": [], "ability_params": {},
        "race": "Warlock", "level": 1, "cost": 60,
        "symbol": "Ce",
    },
    "Gargoyle": {
        "attack": 4, "defense": 7, "hp": 15, "speed": 6,
        "damage_min": 2, "damage_max": 3,
        "shots": 0, "grown": 6, "count": 6,
        "is_archer": False, "is_flying": True, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Warlock", "level": 2, "cost": 200,
        "symbol": "Ga",
    },
    "Griffin": {
        "attack": 6, "defense": 6, "hp": 25, "speed": 4,
        "damage_min": 3, "damage_max": 5,
        "shots": 0, "grown": 4, "count": 4,
        "is_archer": False, "is_flying": True, "is_wide": True,
        "abilities": ["unlimited_retaliation"], "ability_params": {},
        "race": "Warlock", "level": 3, "cost": 300,
        "symbol": "Gr",
    },
    "Minotaur": {
        "attack": 9, "defense": 8, "hp": 35, "speed": 4,
        "damage_min": 5, "damage_max": 10,
        "shots": 0, "grown": 3, "count": 3,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Warlock", "level": 4, "cost": 400,
        "symbol": "Mi",
    },
    "Minotaur King": {
        "attack": 9, "defense": 8, "hp": 45, "speed": 6,
        "damage_min": 5, "damage_max": 10,
        "shots": 0, "grown": 3, "count": 3,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Warlock", "level": 4, "cost": 500,
        "symbol": "MK",
    },
    "Hydra": {
        "attack": 8, "defense": 9, "hp": 75, "speed": 2,
        "damage_min": 6, "damage_max": 12,
        "shots": 0, "grown": 2, "count": 2,
        "is_archer": False, "is_flying": False, "is_wide": True,
        "abilities": ["all_adjacent_attack", "no_enemy_retaliation"],
        "ability_params": {},
        "race": "Warlock", "level": 5, "cost": 800,
        "symbol": "Hy",
    },
    "Green Dragon": {
        "attack": 12, "defense": 12, "hp": 200, "speed": 4,
        "damage_min": 25, "damage_max": 50,
        "shots": 0, "grown": 1, "count": 1,
        "is_archer": False, "is_flying": True, "is_wide": True,
        "abilities": ["two_cell_melee", "magic_resistance"],
        "ability_params": {"magic_resistance": {"chance": 100}},
        "race": "Warlock", "level": 6, "cost": 3000,
        "symbol": "DG",
    },
    "Red Dragon": {
        "attack": 13, "defense": 13, "hp": 250, "speed": 5,
        "damage_min": 25, "damage_max": 50,
        "shots": 0, "grown": 1, "count": 1,
        "is_archer": False, "is_flying": True, "is_wide": True,
        "abilities": ["two_cell_melee", "magic_resistance"],
        "ability_params": {"magic_resistance": {"chance": 100}},
        "race": "Warlock", "level": 6, "cost": 3500,
        "symbol": "DR",
    },
    "Black Dragon": {
        "attack": 14, "defense": 14, "hp": 300, "speed": 6,
        "damage_min": 25, "damage_max": 50,
        "shots": 0, "grown": 1, "count": 1,
        "is_archer": False, "is_flying": True, "is_wide": True,
        "abilities": ["two_cell_melee", "magic_resistance"],
        "ability_params": {"magic_resistance": {"chance": 100}},
        "race": "Warlock", "level": 6, "cost": 4000,
        "symbol": "DB",
    },

    # ── Wizard (Race::WZRD) ────────────────────────────────────────────
    "Halfling": {
        "attack": 2, "defense": 1, "hp": 3, "speed": 3,
        "damage_min": 1, "damage_max": 3,
        "shots": 12, "grown": 8, "count": 8,
        "is_archer": True, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Wizard", "level": 1, "cost": 50,
        "symbol": "Ha",
    },
    "Boar": {
        "attack": 5, "defense": 4, "hp": 15, "speed": 6,
        "damage_min": 2, "damage_max": 3,
        "shots": 0, "grown": 6, "count": 6,
        "is_archer": False, "is_flying": False, "is_wide": True,
        "abilities": [], "ability_params": {},
        "race": "Wizard", "level": 2, "cost": 150,
        "symbol": "Bo",
    },
    "Iron Golem": {
        "attack": 5, "defense": 10, "hp": 30, "speed": 2,
        "damage_min": 4, "damage_max": 5,
        "shots": 0, "grown": 4, "count": 4,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": ["elemental_spell_reduction"],
        "ability_params": {"elemental_spell_reduction": {"factor": 0.5}},
        "race": "Wizard", "level": 3, "cost": 300,
        "symbol": "IG",
    },
    "Steel Golem": {
        "attack": 7, "defense": 10, "hp": 35, "speed": 3,
        "damage_min": 4, "damage_max": 5,
        "shots": 0, "grown": 4, "count": 4,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": ["elemental_spell_reduction"],
        "ability_params": {"elemental_spell_reduction": {"factor": 0.5}},
        "race": "Wizard", "level": 3, "cost": 350,
        "symbol": "SG",
    },
    "Roc": {
        "attack": 7, "defense": 7, "hp": 40, "speed": 4,
        "damage_min": 4, "damage_max": 8,
        "shots": 0, "grown": 3, "count": 3,
        "is_archer": False, "is_flying": True, "is_wide": True,
        "abilities": [], "ability_params": {},
        "race": "Wizard", "level": 4, "cost": 400,
        "symbol": "Ro",
    },
    "Mage": {
        "attack": 11, "defense": 7, "hp": 30, "speed": 5,
        "damage_min": 7, "damage_max": 9,
        "shots": 12, "grown": 2, "count": 2,
        "is_archer": True, "is_flying": False, "is_wide": False,
        "abilities": ["no_melee_penalty"], "ability_params": {},
        "race": "Wizard", "level": 5, "cost": 600,
        "symbol": "Ma",
    },
    "Archmage": {
        "attack": 12, "defense": 8, "hp": 35, "speed": 6,
        "damage_min": 7, "damage_max": 9,
        "shots": 24, "grown": 2, "count": 2,
        "is_archer": True, "is_flying": False, "is_wide": False,
        "abilities": ["no_melee_penalty", "spell_caster"],
        "ability_params": {"spell_caster": {"spell": "dispel", "chance": 20}},
        "race": "Wizard", "level": 5, "cost": 700,
        "symbol": "AM",
    },
    "Giant": {
        "attack": 13, "defense": 10, "hp": 150, "speed": 4,
        "damage_min": 20, "damage_max": 30,
        "shots": 0, "grown": 1, "count": 1,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": [], "ability_params": {},
        "race": "Wizard", "level": 6, "cost": 2000,
        "symbol": "Gi",
    },
    "Titan": {
        "attack": 15, "defense": 15, "hp": 300, "speed": 6,
        "damage_min": 20, "damage_max": 30,
        "shots": 24, "grown": 1, "count": 1,
        "is_archer": True, "is_flying": False, "is_wide": False,
        "abilities": ["no_melee_penalty"], "ability_params": {},
        "race": "Wizard", "level": 6, "cost": 5000,
        "symbol": "Ti",
    },

    # ── Necromancer (Race::NECR) ───────────────────────────────────────
    "Skeleton": {
        "attack": 4, "defense": 3, "hp": 4, "speed": 4,
        "damage_min": 2, "damage_max": 3,
        "shots": 0, "grown": 8, "count": 8,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": ["undead"], "ability_params": {},
        "race": "Necromancer", "level": 1, "cost": 75,
        "symbol": "Sk",
    },
    "Zombie": {
        "attack": 5, "defense": 2, "hp": 15, "speed": 2,
        "damage_min": 2, "damage_max": 3,
        "shots": 0, "grown": 6, "count": 6,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": ["undead"], "ability_params": {},
        "race": "Necromancer", "level": 2, "cost": 150,
        "symbol": "Zo",
    },
    "Mutant Zombie": {
        "attack": 5, "defense": 2, "hp": 20, "speed": 4,
        "damage_min": 2, "damage_max": 3,
        "shots": 0, "grown": 6, "count": 6,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": ["undead"], "ability_params": {},
        "race": "Necromancer", "level": 2, "cost": 200,
        "symbol": "MZ",
    },
    "Mummy": {
        "attack": 6, "defense": 6, "hp": 25, "speed": 4,
        "damage_min": 3, "damage_max": 4,
        "shots": 0, "grown": 4, "count": 4,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": ["undead", "spell_caster"],
        "ability_params": {"spell_caster": {"spell": "curse", "chance": 20}},
        "race": "Necromancer", "level": 3, "cost": 250,
        "symbol": "Mu",
    },
    "Royal Mummy": {
        "attack": 6, "defense": 6, "hp": 30, "speed": 5,
        "damage_min": 3, "damage_max": 4,
        "shots": 0, "grown": 4, "count": 4,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": ["undead", "spell_caster"],
        "ability_params": {"spell_caster": {"spell": "curse", "chance": 30}},
        "race": "Necromancer", "level": 3, "cost": 300,
        "symbol": "RM",
    },
    "Vampire": {
        "attack": 8, "defense": 6, "hp": 30, "speed": 4,
        "damage_min": 5, "damage_max": 7,
        "shots": 0, "grown": 3, "count": 3,
        "is_archer": False, "is_flying": True, "is_wide": False,
        "abilities": ["undead", "no_enemy_retaliation"], "ability_params": {},
        "race": "Necromancer", "level": 4, "cost": 500,
        "symbol": "Vp",
    },
    "Vampire Lord": {
        "attack": 8, "defense": 6, "hp": 40, "speed": 5,
        "damage_min": 5, "damage_max": 7,
        "shots": 0, "grown": 3, "count": 3,
        "is_archer": False, "is_flying": True, "is_wide": False,
        "abilities": ["undead", "no_enemy_retaliation", "hp_drain"],
        "ability_params": {},
        "race": "Necromancer", "level": 4, "cost": 650,
        "symbol": "VL",
    },
    "Lich": {
        "attack": 7, "defense": 12, "hp": 25, "speed": 5,
        "damage_min": 8, "damage_max": 10,
        "shots": 12, "grown": 2, "count": 2,
        "is_archer": True, "is_flying": False, "is_wide": False,
        "abilities": ["undead", "area_shot"], "ability_params": {},
        "race": "Necromancer", "level": 5, "cost": 750,
        "symbol": "Li",
    },
    "Power Lich": {
        "attack": 7, "defense": 13, "hp": 35, "speed": 6,
        "damage_min": 8, "damage_max": 10,
        "shots": 24, "grown": 2, "count": 2,
        "is_archer": True, "is_flying": False, "is_wide": False,
        "abilities": ["undead", "area_shot"], "ability_params": {},
        "race": "Necromancer", "level": 5, "cost": 900,
        "symbol": "PL",
    },
    "Bone Dragon": {
        "attack": 11, "defense": 9, "hp": 150, "speed": 4,
        "damage_min": 25, "damage_max": 45,
        "shots": 0, "grown": 1, "count": 1,
        "is_archer": False, "is_flying": True, "is_wide": True,
        "abilities": ["undead"], "ability_params": {},
        "race": "Necromancer", "level": 6, "cost": 1500,
        "symbol": "BD",
    },

    # ── Neutral (Race::NONE) ───────────────────────────────────────────
    "Rogue": {
        "attack": 6, "defense": 1, "hp": 4, "speed": 5,
        "damage_min": 1, "damage_max": 2,
        "shots": 0, "grown": 8, "count": 8,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": ["no_enemy_retaliation"], "ability_params": {},
        "race": "Neutral", "level": 1, "cost": 50,
        "symbol": "Ro",
    },
    "Nomad": {
        "attack": 7, "defense": 6, "hp": 20, "speed": 6,
        "damage_min": 2, "damage_max": 5,
        "shots": 0, "grown": 4, "count": 4,
        "is_archer": False, "is_flying": False, "is_wide": True,
        "abilities": [], "ability_params": {},
        "race": "Neutral", "level": 2, "cost": 200,
        "symbol": "No",
    },
    "Ghost": {
        "attack": 8, "defense": 7, "hp": 20, "speed": 5,
        "damage_min": 4, "damage_max": 6,
        "shots": 0, "grown": 3, "count": 3,
        "is_archer": False, "is_flying": True, "is_wide": False,
        "abilities": ["soul_eater", "undead"], "ability_params": {},
        "race": "Neutral", "level": 3, "cost": 1000,
        "symbol": "Gh",
    },
    "Genie": {
        "attack": 10, "defense": 9, "hp": 50, "speed": 6,
        "damage_min": 20, "damage_max": 30,
        "shots": 0, "grown": 2, "count": 2,
        "is_archer": False, "is_flying": True, "is_wide": False,
        "abilities": ["enemy_halving"],
        "ability_params": {"enemy_halving": {"chance": 10}},
        "race": "Neutral", "level": 6, "cost": 650,
        "symbol": "Ge",
    },
    "Medusa": {
        "attack": 8, "defense": 9, "hp": 35, "speed": 4,
        "damage_min": 6, "damage_max": 10,
        "shots": 0, "grown": 5, "count": 5,
        "is_archer": False, "is_flying": False, "is_wide": True,
        "abilities": ["spell_caster"],
        "ability_params": {"spell_caster": {"spell": "petrify", "chance": 20}},
        "race": "Neutral", "level": 4, "cost": 500,
        "symbol": "Me",
    },
    "Earth Elemental": {
        "attack": 8, "defense": 8, "hp": 50, "speed": 3,
        "damage_min": 4, "damage_max": 5,
        "shots": 0, "grown": 4, "count": 4,
        "is_archer": False, "is_flying": False, "is_wide": False,
        # fheroes2 MonsterAbilityType::EARTH_CREATURE — deals ×2 to anyone
        # with MonsterWeaknessType::DOUBLE_DAMAGE_FROM_EARTH_CREATURES
        # (battle_troop.cpp:567-577).
        "abilities": ["earth_creature"], "ability_params": {},
        "weaknesses": ["fire"],
        "race": "Neutral", "level": 4, "cost": 500,
        "symbol": "EE",
    },
    "Air Elemental": {
        "attack": 7, "defense": 7, "hp": 35, "speed": 6,
        "damage_min": 2, "damage_max": 8,
        "shots": 0, "grown": 4, "count": 4,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": ["air_creature"], "ability_params": {},
        "weaknesses": ["earth"],
        "race": "Neutral", "level": 4, "cost": 500,
        "symbol": "AE",
    },
    "Fire Elemental": {
        "attack": 8, "defense": 6, "hp": 40, "speed": 5,
        "damage_min": 4, "damage_max": 6,
        "shots": 0, "grown": 4, "count": 4,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": ["fire_creature"], "ability_params": {},
        "weaknesses": ["water"],
        "race": "Neutral", "level": 4, "cost": 500,
        "symbol": "FE",
    },
    "Water Elemental": {
        "attack": 6, "defense": 8, "hp": 45, "speed": 4,
        "damage_min": 3, "damage_max": 7,
        "shots": 0, "grown": 4, "count": 4,
        "is_archer": False, "is_flying": False, "is_wide": False,
        "abilities": ["water_creature"], "ability_params": {},
        "weaknesses": ["air"],
        "race": "Neutral", "level": 4, "cost": 500,
        "symbol": "WE",
    },
}

# ── Unit tags for spell targeting (M7b) ─────────────────────────
# Used by Death Ripple (non-undead), Holy Word (undead only),
# Dragon Slayer (dragons), etc.

UNIT_TAGS = {
    # Undead
    "Skeleton": ["undead"], "Zombie": ["undead"], "Mutant Zombie": ["undead"],
    "Mummy": ["undead"], "Royal Mummy": ["undead"],
    "Vampire": ["undead"], "Vampire Lord": ["undead"],
    "Lich": ["undead"], "Power Lich": ["undead"],
    "Bone Dragon": ["undead", "dragon", "bone_dragon_morale"], "Ghost": ["undead"],
    # Dragon
    "Green Dragon": ["dragon"], "Red Dragon": ["dragon"],
    "Black Dragon": ["dragon"],
    # Elemental
    "Earth Elemental": ["elemental"], "Air Elemental": ["elemental"],
    "Fire Elemental": ["elemental"], "Water Elemental": ["elemental"],
}

# ── Unit type index for observation encoding (T8) ──────────────
# Canonical alphabetical ordering.  Index 0 is reserved for "no unit"
# (used as padding_idx in the embedding layer).  Real units map to 1–63.

UNIT_TYPE_LIST = sorted(UNIT_TYPES.keys())
UNIT_TYPE_INDEX = {name: i + 1 for i, name in enumerate(UNIT_TYPE_LIST)}
NUM_UNIT_TYPES = len(UNIT_TYPE_LIST) + 1

# ── Chinese unit names ──────────────────────────────────────────
UNIT_NAMES_CN = {
    "Air Elemental": "气元素", "Archer": "弓箭手", "Archmage": "大法师",
    "Battle Dwarf": "战斗矮人", "Black Dragon": "黑龙", "Boar": "野猪",
    "Bone Dragon": "骨龙", "Cavalry": "骑兵", "Centaur": "半人马",
    "Champion": "冠军骑士", "Crusader": "十字军", "Cyclops": "独眼巨人",
    "Druid": "德鲁伊", "Dwarf": "矮人", "Earth Elemental": "土元素",
    "Elf": "精灵", "Fire Elemental": "火元素", "Gargoyle": "石像鬼",
    "Genie": "神怪", "Ghost": "幽灵", "Giant": "巨人", "Goblin": "哥布林",
    "Grand Elf": "大精灵", "Greater Druid": "大德鲁伊", "Green Dragon": "绿龙",
    "Griffin": "狮鹫", "Halfling": "半身人", "Hydra": "九头蛇",
    "Iron Golem": "铁魔像", "Lich": "巫妖", "Mage": "法师",
    "Master Swordsman": "剑士大师", "Medusa": "美杜莎", "Minotaur": "牛头人",
    "Minotaur King": "牛头王", "Mummy": "木乃伊", "Mutant Zombie": "变异僵尸",
    "Nomad": "游牧民", "Ogre": "食人魔", "Ogre Lord": "食人魔王",
    "Orc": "兽人", "Orc Chief": "兽人酋长", "Paladin": "圣骑士",
    "Peasant": "农民", "Phoenix": "凤凰", "Pikeman": "枪兵",
    "Power Lich": "强力巫妖", "Ranger": "游侠", "Red Dragon": "红龙",
    "Roc": "巨鹏", "Rogue": "盗贼", "Royal Mummy": "皇家木乃伊",
    "Skeleton": "骷髅兵", "Sprite": "精灵", "Steel Golem": "钢魔像",
    "Swordsman": "剑士", "Titan": "泰坦", "Troll": "巨魔",
    "Unicorn": "独角兽", "Vampire": "吸血鬼", "Vampire Lord": "吸血鬼王",
    "Veteran Pikeman": "精英枪兵", "War Troll": "战争巨魔",
    "Water Elemental": "水元素", "Wolf": "狼", "Zombie": "僵尸",
}
